accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.TgAccountListView.as_view(), name='account-list'),
    path('delete/<int:pk>', views.TgAccountDeleteView.as_view(), name='account-delete'),
    path('detail/<int:pk>', views.TgAccountDetailView.as_view(), name='account-detail'),
    path('create/', views.TgAccountCreateView.as_view(), name='account-create'),
    path('create/otp/<int:phone_num>', views.get_otp, name='account-otp'),
    path('account-list',views.get_account_details,name="account-list-detail")
]

cadence/urls.py
from django.urls import path

from . import views

app_name = 'cadence'

urlpatterns = [
    path('list/', views.CadenceListView.as_view(), name='cadence-list'),
    path('delete/<int:pk>', views.CadenceDeleteView.as_view(), name='cadence-delete'),
    path('detail/<int:pk>', views.cadence_detail, name='cadence-detail'),
    path('execute/<int:pk>', views.cadence_execute, name='cadence-execute'),
    path('create/', views.CadenceCreateView.as_view(), name='cadence-create'),
    path('duplicate/<int:pk>',views.duplicated_cadence,name="cadence-duplicate"),
    path('import/<int:pk>',views.cadence_import,name="cadence-import")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cadence/', include('cadence.urls', namespace='cadence')),
    path('message/', include('message_scripts.urls', namespace='message')),
    path('account/', include('accounts.urls', namespace='account')),
    path('user/', include('users.urls', namespace='user')),
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home-page')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    # path('list/', views.UserListView.as_view(), name='user-list'),
    path('create/', views.UserCreateView.as_view(), name='user-create'),
    path('delete/<int:pk>', views.UserDeleteView.as_view(), name='user-delete'),
    path('login/', views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', views.CustomLogoutView.as_view(), name='user-logout'),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, 'core/index.html')

templates/core/index.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/core/home-page.css' %}">
{% endblock %}


{% block title %}
    Welcome to Vscale Cadence
{% endblock %}


{% block body %}
    {% include "partials/nav.html" %}

    <div class="home-contents text-center pt-5 vertical-center">
        <div class="container">
            <div class="col-md-8 m-auto">

                {% if not request.user.is_authenticated %}
                    <img src="{% static 'images/core.svg' %}" alt="" style="width: 320px;">
                    <h1 style="font-size: 35px;font-weight: 700;" class="mt-3 mb-2">VScale CRM</h1>
                    <h5>CRM helps to manage your leads</h5>
                    <button class="btn-md btn-success btn" onclick="location.href='{% url 'user:user-login' %}'">Login
                    </button>
                    <button class="btn-md btn-primary btn" onclick="location.href='{% url 'user:user-create' %}'">Create
                        Account
                    </button>

                {% else %}
                    {% if request.user.is_staff %}
                        <button class="leadsBtn" onclick="location.href='/admin'">Admin</button>
{#                         <button class="leadsBtn" onclick="location.href='{% url 'user:user-list' %}'">#}
{#                            All Users#}
{#                        </button>#}
                    {% else %}
                        <button class="leadsBtn" onclick="location.href='{% url 'account:account-list' %}'">
                            Accounts
                        </button>
                        <button class="leadsBtn" onclick="location.href='{% url 'cadence:cadence-list' %}'">Cadences
                        </button>
{#                        <button class="leadsBtn" onclick="location.href='{% url 'tg_message:message-view' %}'">#}
{#                            Messages#}
{#                        </button>#}
                    {% endif %}
                    <button class="btn-danger btn"
                            onclick="location.href='{% url 'user:user-delete' request.user.pk %}'">Delete
                    </button>

                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}