cadence/urls.py
from django.urls import path

from . import views

app_name = 'cadence'

urlpatterns = [
    path('list/', views.CadenceListView.as_view(), name='cadence-list'),
    path('delete/<int:pk>', views.CadenceDeleteView.as_view(), name='cadence-delete'),
    path('detail/<int:pk>', views.cadence_detail, name='cadence-detail'),
    path('execute/<int:pk>', views.cadence_execute, name='cadence-execute'),
    path('create/', views.CadenceCreateView.as_view(), name='cadence-create'),
    path('duplicate/<int:pk>',views.duplicated_cadence,name="cadence-duplicate"),
    path('import/<int:pk>',views.cadence_import,name="cadence-import")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cadence/', include('cadence.urls', namespace='cadence')),
    path('message/', include('message_scripts.urls', namespace='message')),
    path('account/', include('accounts.urls', namespace='account')),
    path('user/', include('users.urls', namespace='user')),
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home-page')
]

message_scripts/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    path('<int:c_pk>/update/<int:pk>', views.MessageScriptUpdateView.as_view(), name='message-update'),
    path('<int:c_pk>/delete/<int:pk>', views.MessageScriptDeleteView.as_view(), name='message-delete')
]

cadence/models.py
from django.db import models

from core import models as core_models
from users import models as user_models


class Cadence(core_models.TimeStampedModel):
    user = models.ForeignKey(user_models.User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

cadence/forms.py
from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms

from . import models


class CadenceModelForm(forms.ModelForm):
    class Meta:
        model = models.Cadence

        fields = (
            "name",
        )

        # account = forms.ModelMultipleChoiceField(queryset=)

        widgets = {
            "name": forms.TextInput(attrs={"Placeholder": "Enter Cadence Name", 'autofocus': 'autofocus'}),
        }

        labels = {
            "name": ""
        }


class ExecuteCadenceForm(forms.Form):
    global_time = forms.DateTimeField(widget=DateTimePickerInput(attrs={'Placeholder': 'Datetime'}), label='')
    grp_name = forms.CharField(max_length=255, label='', widget=forms.TextInput(attrs={'Placeholder': 'Grp Name'}))

cadence/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView
from message_scripts.models import MessageScript
from message_scripts import forms as script_form
from scripts.backgroundprocess import schedule_cadence
from . import forms, models
from . import validators
from scripts.functions import fetch_messages_gspread
from accounts.models import Account
from cadence.functions import create_mass_messages

class CadenceCreateView(CreateView):
    template_name = 'cadence/cadence-create.html'
    form_class = forms.CadenceModelForm

    def form_valid(self, form):
        cadence = form.save(commit=False)
        cadence.user = self.request.user
        cadence.save()

        return super().form_valid(form)

    success_url = reverse_lazy('cadence:cadence-list')


class CadenceDeleteView(DeleteView):
    template_name = 'cadence/cadence-delete.html'
    model = models.Cadence
    context_object_name = 'cadence'
    success_url = reverse_lazy('cadence:cadence-list')


class CadenceListView(ListView):
    template_name = 'cadence/cadence-list.html'
    model = models.Cadence

    context_object_name = 'cadence'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


def cadence_detail(request, pk):
    cadence = models.Cadence.objects.get(pk=pk)
    messages_script = cadence.messagescript_set.all()
    form = script_form.MessageScriptModelForm()

    context = {
        'pk': pk,
        'form': form,
        'messages_scripts': messages_script
    }

    if request.method == 'POST':
        form = script_form.MessageScriptModelForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.cadence = cadence
            form.user = request.user    
            form.save()

    return render(request, 'cadence/cadence-detail.html', context)

def duplicated_cadence(request,pk):
    cadence = models.Cadence.objects.get(pk=pk)
    messages_script = cadence.messagescript_set.all()
    
    
    duplicate_cadence = models.Cadence.objects.create(user=cadence.user,name=f"{cadence.name}_duplicated")
    for message_script in messages_script:
        cadence_ = duplicate_cadence
        account = message_script.account
        message = message_script.message
        time_days = message_script.time_days
        time_hours = message_script.time_hours
        time_minutes = message_script.time_minutes
        time_seconds = message_script.time_seconds

        MessageScript.objects.create(cadence=cadence_,account=account,message=message,time_days=time_days,time_hours=time_hours,time_minutes=time_minutes,time_seconds=time_seconds)
        

    return redirect("cadence:cadence-list")
    
def cadence_execute(request, pk):
    cadence = models.Cadence.objects.get(pk=pk)
    form = forms.ExecuteCadenceForm()
    
    context = {
        'form': form,
        'pk': pk
    }
    if request.method == 'POST':
        form = forms.ExecuteCadenceForm(request.POST)
        if form.is_valid():
            datetime = form.cleaned_data['global_time']
            grps_name = form.cleaned_data['grp_name'].split(",")
            
            for groups in grps_name:
                schedule_cadence(cadence, groups, datetime)
                
            messages.info(request, 'Cadence Executed')
        return redirect(reverse_lazy('cadence:cadence-list'))

    return render(request, 'cadence/cadence-execute.html', context)


def cadence_import(request,pk):

    cadence = models.Cadence.objects.get(pk=pk)
    messages_scripts = MessageScript.objects.all().filter(cadence=cadence)
    accounts = Account.objects.all().filter(user=request.user)

    if request.method=="POST":
        url = request.POST["url"]
        sheet_no = int(request.POST["sheet_no"])
        names_col = int(request.POST["names_col"])
        messages_col = int(request.POST["messages_col"])
        starting_row = int(request.POST["starting_row"])
        ending_row = int(request.POST["ending_row"])
        days = int(request.POST["days"])
        hours =  int(request.POST["hours"])
        minutes =  int(request.POST["minutes"])
        seconds =  int(request.POST["seconds"])
        

        #  validation check
        args = [sheet_no,names_col,messages_col,starting_row,ending_row,days,hours,minutes,seconds]
        validators.cadence_import_args_validator(request, url, args)

        # fetch messages from url : starting_row to ending_row -> int
        try:
            names,messages_list = fetch_messages_gspread(url,sheet_no,starting_row,ending_row,names_col,messages_col)
        except Exception as e:
            print("error log",e)
            messages.error(request, f"{e}")
            return redirect("cadence:cadence-detail",pk)

        # create message_scripts from messages and accounts
        create_mass_messages(names,messages_list,cadence,days,hours,minutes,seconds)
        messages.info(request,"imported messages")
        

    context = {
        "cadence_name":cadence.name,
        "messages_scripts":messages_scripts,
        "pk":pk,
        "accounts":accounts
    }


    return render(request,"cadence/cadence-import.html",context)

templates/cadence/cadence-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Cadence
{% endblock %}

{% block body %}

    <div class="loginBox">
        <div class="container">
            <div class="col text-center mt-3">
                <h4 class="mb-4">Create New Cadence</h4>
                <form method="POST" class="form-control col-md-6 justify-content-center m-auto">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-success mt-2" type="submit">Create</button>
                </form>
                {#                <button class="btn btn-info mt-2" onclick="location.href='{% url 'tg_account:account-list' %}'">Go Back</button>#}

            </div>
        </div>
    </div>



{% endblock %}

templates/cadence/cadence-delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete {{ cadence.name }}
{% endblock %}

{% block body %}

    <div class="loginBox">
        <div class="container mt-4">
            <div class="col text-center">

                <form method="post"
                      class="form-control col-md-6 justify-content-center m-auto">
                    <h4 class="mb-4">Are You Sure?</h4>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-danger mt-2">Yes</button>
                    <a href="{{ view.success_url }}" class="btn btn-primary mt-2">Cancel</a>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

templates/cadence/cadence-detail.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}
{% block head %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {{ form.media }}
{% endblock %}


{% block title %}
    Cadence Detail
{% endblock %}

{% block body %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-6">
                <h3>Script</h3>
                {% for message in messages_scripts %}
                    <div><strong>{{ message.account }}</strong> <i class="fas fa-long-arrow-alt-right"></i> {{ message.message }}
                        <strong><em>at</em></strong> {{ message.time_days }}: {{ message.time_hours }}: {{ message.time_minutes }}: {{ message.time_seconds }}-
                        <a href="{% url 'message:message-update' pk message.pk %}">Update</a>-
                        <a href="{% url 'message:message-delete' pk message.pk %}">Delete</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="loginBox">
        <div class="container">
            <div class="col text-center mt-3">
                <h4 class="mb-4">Create New Message</h4>
                <form method="POST" class="col-md-6 justify-content-center m-auto">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-success mt-2" type="submit">Create</button>

                </form>
                <button class="btn btn-info mt-2" onclick="location.href='{% url 'cadence:cadence-list' %}'">Go
                    Back
                </button>
                <a href="{% url 'cadence:cadence-execute' pk %}?page=detail" class="btn btn-secondary mt-2">Execute</a>
                <a href="{% url 'cadence:cadence-duplicate' pk %}" class="btn btn-warning mt-2">Duplicate</a>
                <a href="{% url 'cadence:cadence-import' pk %}" class="btn btn-dark mt-2">Import Messages</a>
                
            </div>
        </div>
    </div>

{% endblock %}

templates/cadence/cadence-execute.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {{ form.media }}
{% endblock %}

{% block title %}
    Execute Cadence
{% endblock %}

{% block body %}
    <div class="loginBox">
        <div class="container">
            <div class="col text-center mt-3">
                <h4 class="mb-4">Execute Cadence</h4>
                <form method="POST" class="col-md-6 justify-content-center m-auto">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-success mt-2" type="submit">Execute</button>
                </form>
                {% if 'page' in request.get_full_path %}
                   <a href="{% url 'cadence:cadence-detail' pk %}" class="btn btn-secondary mt-2">Go Back</a>
                {% else %}
                    <a href="{% url 'cadence:cadence-list' %}" class="btn btn-secondary mt-2">Go Back</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/cadence/cadence-import.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}
{% block head %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <style>
        .row1{
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
    </style>
    {{ form.media }}
{% endblock %}


{% block title %}
    Cadence Import
{% endblock %}

{% block body %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="loginBox">
        <div class="container">
            <div class="col text-center mt-3">
                <h4 class="mb-4">Cadence: {{cadence_name}}</h4>
                <form method="POST" class="col-md-6 justify-content-center m-auto">
                    {% csrf_token %}
                    
                    <div class="row1">
                        <label for="url">Spreadsheet url: </label>
                        <input type="text" name="url" placeholder="https://">
                    </div>
                    <div class="row1">
                        <label for="sheet_no">Sheet No: </label>
                        <input type="number" name="sheet_no" value="0">
                    </div>
                    <div class="row1">
                        <label for="names_col">Names Column No: </label>
                        <input type="number" name="names_col" value="0">
                    </div>
                    <div class="row1">
                        <label for="messages_col">Messages Column No: </label>
                        <input type="number" name="messages_col" value="0">
                    </div>
                    <div class="row1">
                        <label for="starting_row">Starting Row: </label>
                        <input type="number" name="starting_row" value="0">
                    </div>
                    <div class="row1">
                        <label for="ending_row">Ending Row: </label>
                        <input type="number" name="ending_row" value="0">
                    </div>
                    <div class="row1">
                        <label for="days">Delay Days: </label>
                        <input type="number" name="days" value="0">
                    </div>
                    <div class="row1">
                        <label for="hours">Delay Hours: </label>
                        <input type="number" name="hours" value="0">
                    </div>
                    <div class="row1">
                        <label for="minutes">Delay Minutes: </label>
                        <input type="number" name="minutes" value="0">
                    </div>
                    <div class="row1">
                        <label for="seconds">Delay Seconds: </label>
                        <input type="number" name="seconds" value="0">
                    </div>
                    <style>
                        .accouns-display{
                            display: flex;
                            flex-direction: column;
                            border: 2px solid black;
                            align-items: center;
                            
                        }
                        .accouns-display h3{
                            color: brown;
                            font-weight: bold;
                        }
                        .accounts{
                            width: inherit;
                            display: flex; 
                            flex-direction: column; 
                            margin-top: 3px;   
                            width: 100%;
                            align-items: center;
                        }
                        
                    </style>
                    <div class="accouns-display">
                        <h3>Accounts</h3>
                        <div class="accounts">
                            {% for account in accounts%} 
                               <p>{{account.acc_name}}</p>
                            {% endfor %}
                            
                        </div>
                    </div>
                    
                    <a href="{% url 'cadence:cadence-detail' pk %}" class="btn btn-warning mt-2">back</a>
                    <button class="btn btn-success mt-2" type="submit">Fetch Messages</button>

                </form>
                
            </div>
        </div>
    </div>


    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-6">
                <h3>Script</h3>
                {% for message in messages_scripts %}
                    <div><strong>{{ message.account }}</strong> <i class="fas fa-long-arrow-alt-right"></i> {{ message.message }}
                        <strong><em>at</em></strong> {{ message.time_days }}: {{ message.time_hours }}: {{ message.time_minutes }}: {{ message.time_seconds }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/cadence/cadence-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/contacts/contact-list.css' %}">
{% endblock %}

{% block title %}
    Cadence List
{% endblock %}

{% block body %}
    {% include "partials/nav.html" %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <section class="contacts">
        <div class="container">
            <div class="top d-flex m-auto">
                <div class="col-md-6">
                    <h1>Cadences</h1>
                    <button class="btn-md btn-success btn" onclick="location.href='{% url 'cadence:cadence-create' %}'">
                        Create New Cadence
                    </button>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead">
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Execute</th>
                    <th scope="col">Delete</th>

                    </thead>
                    <tbody>
                    {% for cadence in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{% url 'cadence:cadence-detail' cadence.pk %}">{{ cadence.name }}</a></td>
                            <td><a href="{% url 'cadence:cadence-execute' cadence.pk %}">Execute</a></td>

                            <td>
                                <a href="{% url 'cadence:cadence-delete' cadence.pk %}">❌
                                </a>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>

{% endblock %}